[server]
headless = true
port = 8080
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"

[logger]
level = "debug"
messageFormat = "%(asctime)s — %(levelname)s — %(message)s"
